/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  publishedAt: string;
  category: string;
  tags: Array<string>;
  featured?: boolean;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: sanityPostSummariesQuery
// Query: *[_type == "post" && defined(slug.current)]    | order(featured desc, publishedAt desc) {      title,      description,      publishedAt,      category,      tags,      featured,      seoTitle,      seoDescription,      "slug": slug.current,      mainImage,      "bodyPreview": body[]{        _type,        children[]{          _type,          _key,          text,          marks        }      }    }[$start...$end]
export type SanityPostSummariesQueryResult = Array<{
  title: string;
  description: string;
  publishedAt: string;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
  seoTitle: string | null;
  seoDescription: string | null;
  slug: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  bodyPreview: Array<
    | {
        _type: "block";
        children: Array<{
          _type: "span";
          _key: string;
          text: string | null;
          marks: Array<string> | null;
        }> | null;
      }
    | {
        _type: "image";
        children: null;
      }
  >;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: sanityPostCountQuery
// Query: count(*[_type == "post" && defined(slug.current)])
export type SanityPostCountQueryResult = number;

// Source: src/sanity/lib/queries.ts
// Variable: sanityPostsQuery
// Query: *[_type == "post" && defined(slug.current)]    | order(featured desc, publishedAt desc) {      title,      description,      publishedAt,      category,      tags,      featured,      seoTitle,      seoDescription,      "slug": slug.current,      mainImage,      body    }
export type SanityPostsQueryResult = Array<{
  title: string;
  description: string;
  publishedAt: string;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
  seoTitle: string | null;
  seoDescription: string | null;
  slug: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
        _key: string;
      }
  >;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: sanityPostBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    title,    description,    publishedAt,    category,    tags,    featured,    seoTitle,    seoDescription,    "slug": slug.current,    mainImage,    body  }
export type SanityPostBySlugQueryResult = {
  title: string;
  description: string;
  publishedAt: string;
  category: string;
  tags: Array<string>;
  featured: boolean | null;
  seoTitle: string | null;
  seoDescription: string | null;
  slug: string;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        _type: "image";
        _key: string;
      }
  >;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(featured desc, publishedAt desc) {\n      title,\n      description,\n      publishedAt,\n      category,\n      tags,\n      featured,\n      seoTitle,\n      seoDescription,\n      "slug": slug.current,\n      mainImage,\n      "bodyPreview": body[]{\n        _type,\n        children[]{\n          _type,\n          _key,\n          text,\n          marks\n        }\n      }\n    }[$start...$end]\n': SanityPostSummariesQueryResult;
    '\n  count(*[_type == "post" && defined(slug.current)])\n': SanityPostCountQueryResult;
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(featured desc, publishedAt desc) {\n      title,\n      description,\n      publishedAt,\n      category,\n      tags,\n      featured,\n      seoTitle,\n      seoDescription,\n      "slug": slug.current,\n      mainImage,\n      body\n    }\n': SanityPostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    title,\n    description,\n    publishedAt,\n    category,\n    tags,\n    featured,\n    seoTitle,\n    seoDescription,\n    "slug": slug.current,\n    mainImage,\n    body\n  }\n': SanityPostBySlugQueryResult;
  }
}
