import { Services } from "@/types/services";

export const services: Services[] = [
  {
    id: "1",
    slug: "regular-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-1.jpeg",
    service_title: "Regular Cleaning",
    description:
      "Our Regular Cleaning service ensures your home stays fresh, organized, and hygienic with consistent upkeep. Perfect for weekly or bi-weekly maintenance, this service tackles everyday messes, keeps surfaces dust-free, and maintains your bathroom and kitchen to a sparkling finish. We help you maintain a healthy, welcoming home environment without lifting a finger.",
    duration: "2-3 hours",
    rating: "4.8",
    price: "120",
    about_services: [
      "Ideal for weekly or bi-weekly upkeep.",
      "Focuses on maintaining overall home cleanliness.",
      "Recommended for busy individuals or families.",
      "Helps reduce allergens and bacteria regularly.",
    ],
    features: [
      "Dust all surfaces",
      "Vacuum carpets & rugs",
      "Clean bathrooms and kitchen",
      "Mop hard floors",
    ],
    cleaning_process: [
      "Initial walk-through and checklist review.",
      "Dusting of all reachable surfaces and fixtures.",
      "Vacuuming of carpets, area rugs, and upholstery.",
      "Surface cleaning of kitchen counters, stovetops, and sinks.",
      "Bathroom cleaning including toilet, tub, mirror, and floors.",
      "Mopping of all hard floors with disinfectant.",
      "Final walkthrough to ensure quality standards.",
    ],
  },
  {
    id: "2",
    slug: "deep-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-2.jpeg",
    service_title: "Deep Cleaning",
    description:
      "Our Deep Cleaning service is a top-to-bottom intensive clean that reaches hidden grime and built-up dirt that regular cleaning may miss. Ideal for seasonal refreshes, post-party cleanups, or first-time appointments, this service revitalizes your space, improves air quality, and ensures every surface sparkles.",
    duration: "4-6 hours",
    rating: "4.0",
    price: "150",
    about_services: [
      "Includes hard-to-reach areas and under furniture.",
      "Perfect before events or after long gaps in cleaning.",
      "Improves indoor air quality and overall hygiene.",
      "Removes built-up dirt and grime.",
    ],
    features: [
      "Detailed kitchen cleaning",
      "Scrub tile & grout",
      "Clean behind furniture",
      "Wipe down all baseboards",
    ],
    cleaning_process: [
      "Inspection and preparation of deep-clean zones.",
      "Heavy dusting including ceiling fans, vents, and light fixtures.",
      "Cleaning behind/under furniture and appliances.",
      "Scrubbing tiles, grout, and tough bathroom stains.",
      "Degreasing kitchen areas including hood, backsplash, and oven.",
      "Wiping baseboards, door frames, and switches.",
      "Final polish and inspection for deep-clean approval.",
    ],
  },
  {
    id: "3",
    slug: "movein-moveout",
    thumbnail_img: "/images/home/servicesoffer/services-img-3.jpg",
    service_title: "Move-in / Move-out",
    description:
      "Our Move-in / Move-out Cleaning service is designed to leave properties spotless for new occupants or move-out inspections. We clean every corner of your empty home, ensuring cabinets, drawers, and appliances are ready for use or presentation. A must-have for tenants, landlords, and property managers.",
    duration: "3-5 hours",
    rating: "4.1",
    price: "200",
    about_services: [
      "Restores property to presentable condition.",
      "Ensures cleanliness for new residents.",
      "Helpful for landlords before/after tenancy.",
      "Includes cleaning of empty cabinets and appliances.",
    ],
    features: [
      "Clean inside cabinets & drawers",
      "Wipe all doors and frames",
      "Appliance interior cleaning",
      "Garage/balcony cleaning (optional)",
    ],
    cleaning_process: [
      "Walkthrough to assess cleaning needs.",
      "Removal of debris and trash left behind.",
      "Deep cleaning of empty cabinets, closets, and drawers.",
      "Full appliance cleaning inside and out.",
      "Scrubbing of bathrooms, kitchen, and floor corners.",
      "Dusting and washing of walls, vents, and trim.",
      "Optional garage and balcony cleaning if requested.",
    ],
  },
  {
    id: "4",
    slug: "removal-storage",
    thumbnail_img: "/images/home/servicesoffer/services-img-4.jpg",
    service_title: "Removal & Storage",
    description:
      "Our Post-Construction Removal & Storage Cleaning service specializes in clearing out the mess left behind after renovations or construction. We eliminate dust, debris, and residue from paint or materials, leaving your property ready for move-in or staging. Essential for newly finished projects.",
    duration: "5-8 hours",
    rating: "3.8",
    price: "230",
    about_services: [
      "Post-renovation clean-up service.",
      "Removes leftover dust, paint splatter, and debris.",
      "Ensures a livable and clean environment post-construction.",
      "Includes high-dust surfaces and window detailing.",
    ],
    features: [
      "Remove dust from all surfaces",
      "Clean walls, vents & windows",
      "Vacuum & mop multiple times",
      "Debris and trash removal",
    ],
    cleaning_process: [
      "Safety check and setup for debris removal.",
      "High-level dusting of ceilings, lights, and HVAC vents.",
      "Wipe down of walls and paint spots removal where possible.",
      "Window washing including tracks and frames.",
      "Thorough vacuuming and multiple rounds of mopping.",
      "Removal of leftover materials, tape, and trash.",
      "Final polish of all surfaces and final client walkthrough.",
    ],
  },
  {
    id: "5",
    slug: "eco-friendly-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-5.jpg",
    service_title: "Eco Cleaning",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    duration: "2-3 hours",
    rating: "3.0",
    price: "90",
    about_services: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
    ],
    features: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    cleaning_process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
  },
  {
    id: "6",
    slug: "post-renovation-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-6.jpg",
    service_title: "Renovation Cleaning",
    description:
      "Post-Renovation Cleaning is designed to eliminate construction dust, debris, and residue after home improvements. This detailed service restores cleanliness and air quality, making your space safe and comfortable again after any renovation or remodeling work.",
    duration: "4-6 hours",
    rating: "3.5",
    price: "160",
    about_services: [
      "Removes fine dust and construction residue.",
      "Cleans paint splatters and adhesive marks.",
      "Improves air quality post-construction.",
      "Prepares your home for safe, fresh re-entry.",
    ],
    features: [
      "HEPA vacuuming of all surfaces",
      "Removal of construction dust from vents and corners",
      "Detailed floor and window cleaning",
      "Wipe-down of walls, fixtures, and appliances",
    ],
    cleaning_process: [
      "Initial assessment to identify construction impact zones.",
      "HEPA vacuuming to capture fine dust particles.",
      "Wiping down all hard surfaces, including baseboards and trim.",
      "Removing paint spots, adhesive, and other residue.",
      "Cleaning light fixtures, vents, and switches.",
      "Mopping and polishing floors for a spotless finish.",
      "Final air circulation and inspection for quality assurance.",
    ],
  }
  
];
