import { Services } from "@/types/services";

export const services: Services[] = [
  {
    id: "1",
    slug: "regular-cleaning",
    thumbnail_img: "/images/services/regular-cleaning.jpg",
    service_title: "Regular Cleaning",
    description:
      "Professional regular cleaning service in Orlando. Weekly or bi-weekly maintenance keeps your home fresh, organized, and hygienic. Dust-free surfaces, sparkling bathrooms and kitchens. Perfect for busy families. Book your cleaning today!",
    duration: "2-3 hours",
    rating: "4.8",
    price: "120",
    about_services: [
      "Ideal for weekly or bi-weekly upkeep.",
      "Focuses on maintaining overall home cleanliness.",
      "Recommended for busy individuals or families.",
      "Helps reduce allergens and bacteria regularly.",
    ],
    features: [
      "Dust all surfaces",
      "Vacuum carpets & rugs",
      "Clean bathrooms and kitchen",
      "Mop hard floors",
    ],
    cleaning_process: [
      "Initial walk-through and checklist review.",
      "Dusting of all reachable surfaces and fixtures.",
      "Vacuuming of carpets, area rugs, and upholstery.",
      "Surface cleaning of kitchen counters, stovetops, and sinks.",
      "Bathroom cleaning including toilet, tub, mirror, and floors.",
      "Mopping of all hard floors with disinfectant.",
      "Final walkthrough to ensure quality standards.",
    ],
  },
  {
    id: "2",
    slug: "deep-cleaning",
    thumbnail_img: "/images/services/deep-cleaning.jpg",
    service_title: "Deep Cleaning",
    description:
      "Our Deep Cleaning service is a top-to-bottom intensive clean that reaches hidden grime and built-up dirt that regular cleaning may miss. Ideal for seasonal refreshes, post-party cleanups, or first-time appointments, this service revitalizes your space, improves air quality, and ensures every surface sparkles.",
    duration: "4-6 hours",
    rating: "4.0",
    price: "150",
    about_services: [
      "Includes hard-to-reach areas and under furniture.",
      "Perfect before events or after long gaps in cleaning.",
      "Improves indoor air quality and overall hygiene.",
      "Removes built-up dirt and grime.",
    ],
    features: [
      "Detailed kitchen cleaning",
      "Scrub tile & grout",
      "Clean behind furniture",
      "Wipe down all baseboards",
    ],
    cleaning_process: [
      "Inspection and preparation of deep-clean zones.",
      "Heavy dusting including ceiling fans, vents, and light fixtures.",
      "Cleaning behind/under furniture and appliances.",
      "Scrubbing tiles, grout, and tough bathroom stains.",
      "Degreasing kitchen areas including hood, backsplash, and oven.",
      "Wiping baseboards, door frames, and switches.",
      "Final polish and inspection for deep-clean approval.",
    ],
  },
  {
    id: "3",
    slug: "move-in-out-cleaning",
    thumbnail_img: "/images/services/move-out-cleaning.jpg",
    service_title: "Move-In / Move-Out Cleaning",
    description:
      "Our Move-In / Move-Out Cleaning service leaves properties spotless for new occupants or move-out inspections. We clean every corner of your empty home, ensuring cabinets, drawers, and appliances are ready for use or presentation.",
    duration: "3-5 hours",
    rating: "4.1",
    price: "200",
    about_services: [
      "Restores property to presentable condition.",
      "Ensures cleanliness for new residents.",
      "Helpful for landlords before/after tenancy.",
      "Includes cleaning of empty cabinets and appliances.",
    ],
    features: [
      "Clean inside cabinets & drawers",
      "Wipe all doors and frames",
      "Appliance interior cleaning",
      "Garage/balcony cleaning (optional)",
    ],
    cleaning_process: [
      "Walkthrough to assess cleaning needs.",
      "Removal of debris and trash left behind.",
      "Deep cleaning of empty cabinets, closets, and drawers.",
      "Full appliance cleaning inside and out.",
      "Scrubbing of bathrooms, kitchen, and floor corners.",
      "Dusting and washing of walls, vents, and trim.",
      "Optional garage and balcony cleaning if requested.",
    ],
  },
  {
    id: "4",
    slug: "post-construction-cleaning",
    thumbnail_img: "/images/services/post-construction-cleaning.jpg",
    service_title: "Post-Construction Cleaning",
    description:
      "Our Post-Construction Cleaning service removes dust, debris, and residue after renovations or new builds, leaving your property clean, safe, and ready for move-in.",
    duration: "5-8 hours",
    rating: "3.8",
    price: "230",
    about_services: [
      "Post-renovation clean-up service.",
      "Removes leftover dust, paint splatter, and debris.",
      "Ensures a livable and clean environment post-construction.",
      "Includes high-dust surfaces and window detailing.",
    ],
    features: [
      "Remove dust from all surfaces",
      "Clean walls, vents & windows",
      "Vacuum & mop multiple times",
      "Debris and trash removal",
    ],
    cleaning_process: [
      "Safety check and setup for debris removal.",
      "High-level dusting of ceilings, lights, and HVAC vents.",
      "Wipe down of walls and paint spots removal where possible.",
      "Window washing including tracks and frames.",
      "Thorough vacuuming and multiple rounds of mopping.",
      "Removal of leftover materials, tape, and trash.",
      "Final polish of all surfaces and final client walkthrough.",
    ],
  },
  {
    id: "5",
    slug: "carpet-cleaning",
    thumbnail_img: "/images/services/carpet-cleaning.jpg",
    service_title: "Carpet Cleaning",
    description:
      "Our Carpet Cleaning service lifts embedded dirt, stains, and allergens from carpets and rugs, restoring softness and freshness for homes and offices.",
    duration: "2-3 hours",
    rating: "3.0",
    price: "90",
    about_services: [
      "Removes deep-set dirt and allergens.",
      "Revives color and texture in carpets and rugs.",
      "Ideal for high-traffic areas and pets.",
      "Safe for families and workplaces.",
    ],
    features: [
      "Pre-treatment for stains",
      "Deep extraction cleaning",
      "Deodorizing finish",
      "Fast-dry recommendations",
    ],
    cleaning_process: [
      "Inspection of carpet condition and stains.",
      "Vacuuming to remove loose debris.",
      "Spot treatment for high-impact areas.",
      "Deep steam or extraction cleaning.",
      "Grooming fibers for even drying.",
      "Final walkthrough and care tips.",
    ],
  },
  {
    id: "6",
    slug: "commercial-cleaning",
    thumbnail_img: "/images/services/commercial-office-cleaning-1.jpg",
    service_title: "Commercial Cleaning",
    description:
      "Our Commercial Cleaning service keeps offices, retail spaces, and commercial properties spotless with reliable, professional care tailored to your business schedule.",
    duration: "4-6 hours",
    rating: "3.5",
    price: "160",
    about_services: [
      "Maintains a clean, professional workspace.",
      "Flexible scheduling for business hours.",
      "Ideal for offices, retail, and shared spaces.",
      "Focus on high-traffic and common areas.",
    ],
    features: [
      "Workspace and desk sanitization",
      "Restroom cleaning and restocking",
      "Floor care and trash removal",
      "Breakroom and lobby detailing",
    ],
    cleaning_process: [
      "Walkthrough to confirm scope and priorities.",
      "Dusting and disinfecting high-touch areas.",
      "Restroom cleaning with stocked supplies.",
      "Vacuuming and mopping across the facility.",
      "Trash removal and surface polishing.",
      "Final inspection before handoff.",
    ],
  }

];
