import { Services } from "@/types/services";

export const services: Services[] = [
  {
    id: "1",
    slug: "regular-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-1.jpg",
    service_title: "Regular Cleaning in Orlando",
    description:
      "Keep your home fresh, organized, and spotless with our professional regular cleaning in Orlando. Designed for weekly or bi-weekly maintenance, this service ensures your space stays consistently clean so you can focus on what truly matters. Our trained team handles every detail with care, using top-quality tools and safe products to maintain a healthy and comfortable home environment.",
    duration: "2-3 hours",
    rating: "4.8",
    price: "120",
    about_services: [
      "Dusting and wiping all accessible surfaces.",
      "Vacuuming carpets, rugs, and high-traffic areas.",
      "Sweeping and mopping all hard floors.",
      "Cleaning and disinfecting bathrooms (toilets, sinks, mirrors, showers—surface level).",
      "Kitchen cleaning: countertops, exterior of appliances, stovetop, microwave interior.",
      "Emptying all trash bins and replacing bags.",
      "Cleaning interior glass on sliding doors and reachable windows.",
      "Light organization of visible areas (no heavy items moved).",
    ],
    features: [
      "Dust all surfaces",
      "Vacuum carpets & rugs",
      "Clean bathrooms and kitchen",
      "Mop hard floors",
    ],
    cleaning_process: [
      "Initial walk-through and checklist review with your cleaning team.",
      "Dusting and wiping all accessible surfaces and fixtures.",
      "Vacuuming of carpets, area rugs, and high-traffic areas.",
      "Sweeping and mopping all hard floors with disinfectant.",
      "Bathroom cleaning including toilets, sinks, mirrors, and showers (surface level).",
      "Kitchen cleaning: countertops, appliance exteriors, stovetop, and microwave interior.",
      "Emptying trash bins, replacing bags, and final quality walkthrough.",
    ],
  },
  {
    id: "2",
    slug: "deep-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-2.jpg",
    service_title: "Deep Cleaning in Orlando",
    description:
      "Give your home a complete, top-to-bottom refresh with our professional deep cleaning in Orlando. This service is designed for homes that need extra attention, detailed scrubbing, and a more intensive approach than regular maintenance. Whether it's your seasonal reset, after hosting guests, or before important events, our deep cleaning restores shine, removes buildup, and revitalizes every area of your home. We use high-efficiency equipment, safe products, and a meticulous checklist to deliver exceptional results.",
    duration: "4-6 hours",
    rating: "4.0",
    price: "150",
    about_services: [
      "Detailed dusting of all reachable surfaces, décor, baseboards, door frames, and window sills.",
      "Deep bathroom cleaning: scrubbing showers, tubs, tiles, grout lines (surface level), toilets, sinks, mirrors.",
      "Kitchen deep clean: stovetop detail, exterior of appliances, microwave interior, cabinet fronts, backsplash.",
      "Vacuuming of carpets, rugs, and upholstery surfaces.",
      "Mopping and disinfecting all hard floors.",
      "Cleaning accessible vents, fans, and high-touch areas.",
      "Detailed cleaning of sliding door tracks, window tracks, and reachable interior glass.",
    ],
    features: [
      "Detailed kitchen cleaning",
      "Scrub tile & grout",
      "Clean behind furniture",
      "Wipe down all baseboards",
    ],
    cleaning_process: [
      "Assessment of your home size, condition, and priorities for deep cleaning.",
      "Detailed dusting from top to bottom: décor, baseboards, door frames, and window sills.",
      "Deep bathroom cleaning including scrubbing showers, tubs, tiles, grout lines, toilets, sinks, and mirrors.",
      "Kitchen deep clean: stovetop detail, appliance exteriors, microwave interior, cabinet fronts, and backsplash.",
      "Vacuuming of carpets, rugs, and upholstery surfaces.",
      "Mopping and disinfecting all hard floors, plus cleaning accessible vents and fans.",
      "Detailed cleaning of sliding door tracks, window tracks, and final quality inspection.",
    ],
  },
  {
    id: "3",
    slug: "movein-moveout",
    thumbnail_img: "/images/home/servicesoffer/services-img-3.jpg",
    service_title: "Move-In / Move-Out Cleaning in Orlando",
    description:
      "Start fresh in your new home or leave your old place spotless with our professional move-in / move-out cleaning in Orlando. This service is designed for empty or nearly empty properties that need a detailed top-to-bottom clean before handing over the keys. We focus on deep sanitizing kitchens, bathrooms, floors, cabinets, and high-touch areas, so landlords, tenants, and owners can enjoy a smooth transition with confidence.",
    duration: "3-5 hours",
    rating: "4.1",
    price: "200",
    about_services: [
      "Detailed dusting of all reachable surfaces, baseboards, doors, and window sills.",
      "Deep cleaning and disinfection of all bathrooms (toilets, sinks, showers, tubs, tiles – surface level).",
      "Kitchen detail: countertops, backsplash, cabinet exteriors, appliance exteriors, microwave interior.",
      "Inside cleaning of empty cabinets and drawers (kitchen and bathrooms).",
      "Inside oven and refrigerator cleaning (if emptied and accessible).",
      "Vacuuming carpets and rugs, including edges and high-traffic areas.",
      "Sweeping and mopping all hard floors.",
      "Cleaning of interior glass on sliding doors and reachable windows.",
    ],
    features: [
      "Clean inside cabinets & drawers",
      "Wipe all doors and frames",
      "Appliance interior cleaning",
      "Trash removal from debris",
    ],
    cleaning_process: [
      "Property assessment: size, number of rooms, and move date consultation.",
      "Detailed dusting of all reachable surfaces, baseboards, doors, and window sills.",
      "Deep cleaning and disinfection of all bathrooms including toilets, sinks, showers, tubs, and tiles.",
      "Kitchen detail: countertops, backsplash, cabinet exteriors, and appliance exteriors.",
      "Inside cleaning of empty cabinets, drawers, and inside oven and refrigerator (if accessible).",
      "Vacuuming carpets and rugs, sweeping and mopping all hard floors, and cleaning interior glass.",
      "Final trash removal from small household debris and quality inspection before key handover.",
    ],
  },
  {
    id: "4",
    slug: "removal-storage",
    thumbnail_img: "/images/home/servicesoffer/services-img-4.jpg",
    service_title: "Removal & Storage in Orlando",
    description:
      "Our Post-Construction Removal & Storage Cleaning service specializes in clearing out the mess left behind after renovations or construction. We eliminate dust, debris, and residue from paint or materials, leaving your property ready for move-in or staging. Essential for newly finished projects.",
    duration: "5-8 hours",
    rating: "3.8",
    price: "230",
    about_services: [
      "Post-renovation clean-up service.",
      "Removes leftover dust, paint splatter, and debris.",
      "Ensures a livable and clean environment post-construction.",
      "Includes high-dust surfaces and window detailing.",
    ],
    features: [
      "Remove dust from all surfaces",
      "Clean walls, vents & windows",
      "Vacuum & mop multiple times",
      "Debris and trash removal",
    ],
    cleaning_process: [
      "Safety check and setup for debris removal.",
      "High-level dusting of ceilings, lights, and HVAC vents.",
      "Wipe down of walls and paint spots removal where possible.",
      "Window washing including tracks and frames.",
      "Thorough vacuuming and multiple rounds of mopping.",
      "Removal of leftover materials, tape, and trash.",
      "Final polish of all surfaces and final client walkthrough.",
    ],
  },
  {
    id: "5",
    slug: "eco-friendly-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-5.jpg",
    service_title: "Eco Cleaning in Orlando",
    description:
      "Eco Cleaning is perfect for environmentally conscious households. We use only biodegradable, non-toxic cleaning products made from plants and essential oils to clean your home safely. This service protects your health and the planet without compromising quality or hygiene.",
    duration: "2-3 hours",
    rating: "3.0",
    price: "90",
    about_services: [
      "Uses plant-based, biodegradable products.",
      "Safe for children, pets, and allergy-prone individuals.",
      "Supports a healthier home and planet.",
      "Ideal for eco-conscious homeowners.",
    ],
    features: [
      "Use of eco-friendly products",
      "Safe for kids and pets",
      "Essential oil-based sanitizers",
      "Microfiber cloth cleaning",
    ],
    cleaning_process: [
      "Consultation on specific sensitivities and preferences.",
      "Application of plant-based cleaners to all surfaces.",
      "Use of microfiber cloths to trap dust and bacteria.",
      "Eco-safe disinfecting of bathrooms and kitchen.",
      "Window and mirror cleaning with vinegar solutions.",
      "Essential oil-infused room freshening.",
      "Final air-out and inspection to ensure eco-standards are met.",
    ],
  },
  {
    id: "6",
    slug: "post-renovation-cleaning",
    thumbnail_img: "/images/home/servicesoffer/services-img-6.jpg",
    service_title: "Post-Construction Cleaning in Orlando",
    description:
      "After a renovation or new build, dust and debris can settle everywhere. Our post-construction cleaning in Orlando is designed to handle this fine dust, remove light paint splatters, and make the space truly ready to use or show. We go beyond regular cleaning by focusing on detailed surfaces, fixtures, and finishes so your property looks polished and move-in ready.",
    duration: "4-6 hours",
    rating: "3.5",
    price: "160",
    about_services: [
      "HEPA vacuuming of floors, corners, and surfaces to remove fine construction dust.",
      "Multi-stage dusting from top to bottom (vents, fixtures, baseboards, doors, window sills).",
      "Wiping down walls where safe and appropriate (surface dust only).",
      "Detailed cleaning of window tracks, frames, and reachable interior glass.",
      "Bathroom deep clean: tiles, fixtures, sinks, toilets, showers, tubs (construction residue removal – light level).",
      "Kitchen clean: countertops, cabinet exteriors, appliance exteriors, sink, backsplash.",
      "Removal of light paint splatters, stickers, tape residue, and labels where possible.",
      "Sweeping and mopping of all hard floors multiple times if needed.",
    ],
    features: [
      "HEPA vacuuming of all surfaces",
      "Removal of construction dust from vents and corners",
      "Detailed floor and window cleaning",
      "Wipe-down of walls, fixtures, and appliances",
    ],
    cleaning_process: [
      "Assessment of your project: size, type of work done, and level of dust/residue.",
      "HEPA vacuuming of floors, corners, and surfaces to remove fine construction dust.",
      "Multi-stage dusting from top to bottom: vents, fixtures, baseboards, doors, and window sills.",
      "Wiping down walls where safe and appropriate, plus detailed cleaning of window tracks and frames.",
      "Bathroom deep clean: tiles, fixtures, sinks, toilets, showers, and tubs (construction residue removal).",
      "Kitchen clean: countertops, cabinet exteriors, appliance exteriors, sink, and backsplash.",
      "Removal of light paint splatters, stickers, tape residue, and final multi-stage mopping for spotless finish.",
    ],
  }

];
