export const WorkData = [
    "/images/home/ourwork/professional-ceiling-cobweb-removal-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-tile-floor-mopping-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-kitchen-stove-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-mirror-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-window-and-blinds-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-upholstery-sofa-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-ceiling-fan-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-air-vent-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-steam-air-vent-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-high-wall-dust-removal-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-refrigerator-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-floor-vacuum-cleaning-orlando-fl.jpg.png",
    "/images/home/ourwork/professional-furniture-dusting-cleaning-orlando-fl.jpg.png",
]
